
# tap "repositories and their packages"

tap "homebrew/core"
brew "anyenv"
brew "asciinema"
brew "autoconf"
brew "bat"
brew "cairo"
brew "exa"
brew "fontconfig"
brew "fontforge"
brew "freetype"
brew "fribidi"
brew "fzf"
brew "fzy"
brew "gawk"
brew "gdbm"
brew "gettext"
brew "ghq"
brew "giflib"
brew "git"
brew "git-recent"
brew "glib"
brew "gmp"
brew "graphite2"
brew "harfbuzz"
brew "hub"
brew "icu4c"
brew "jpeg"
brew "jq"
brew "libevent"
brew "libffi"
brew "libimobiledevice"
brew "libplist"
brew "libpng"
brew "libspiro"
brew "libtasn1"
brew "libtiff"
brew "libtool"
brew "libuninameslist"
brew "libusb"
brew "libyaml"
brew "libzip"
brew "lua"
brew "lzo"
brew "mas"
brew "mpfr"
brew "ncurses"
brew "nkf"
brew "node-build"
brew "nodenv"
brew "oniguruma"
brew "openssl@1.1"
brew "pango"
brew "pcre"
brew "pcre2"
brew "perl"
brew "pixman"
brew "pkg-config"
brew "python"
brew "readline"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rlwrap"
brew "ruby"
brew "sqlite"
brew "the_silver_searcher"
brew "tig"
brew "tldr"
brew "tmux"
brew "translate-shell"
brew "trash"
brew "tree"
brew "unrar"
brew "vim"
brew "watchman"
brew "xz"
brew "yarn" --ignore-dependencies
brew "zplug"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"

tap "homebrew/cask"
cask "1password"
cask "alfred"
cask "bartender"
cask "dash"
cask "google-chrome"
cask "graphiql"
cask "iterm2"
cask "karabiner-elements"
cask "notion"
cask "pomello"
cask "qlmarkdown"
cask "quicklook-csv"
cask "react-native-debugger"
cask "runjs"
cask "sketchpacks"
cask "visual-studio-code"
cask "zeplin"

tap "knqyf263/pet"
brew "pet"

tap "nodenv/nodenv"
brew "jetbrains-npm"

tap "rcmdnk/file"
brew "brew-file"

tap "sanemat/font"
brew "ricty" --with-powerline

# Other Homebrew "packages"
brew "openssl"
brew "usbmuxd"

# Other cask "applications"
cask "BetterZip"
cask "android-studio"
cask "charles"
cask "docker"
cask "gas-mask"
cask "google-japanese-ime"
cask "graphql-playground"
cask "insomnia"
cask "james"
cask "mapture"
cask "pennywise"
cask "qlcolorcode"
cask "qlstephen"
cask "quicklook-json"
cask "rightfont"
cask "sketch"
cask "stack"
cask "typora"
cask "webstorm"

# App Store applications
mas "Designer", id: 824171161 Affinity
mas "Bear", id: 1091189122
mas "GarageBand", id: 682658836
mas "GitStars", id: 1112091009
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "MindNode", id: 1289197285
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixave", id: 924891282
mas "Pixelmator", id: 407963104
mas "Sip", id: 507257563
mas "Tab", id: 458887729 Translate
mas "Tweetbot", id: 1384080005
mas "Unclutter", id: 577085396
