alias -g C='| pbcopy'
alias -g X='| xargs'

alias k='kill -9'
alias zshrc='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias ideavim='vim ~/.ideavimrc'
alias brewfile='vim ~/.config/brewfile/Brewfile'
alias tigrc='vim ~/.tigrc'
alias dotfiles='cd ~/dotfiles'
alias sz='source ~/.zshrc'
alias tmuxconf='vim ~/.tmux.conf'
alias ls='ls -G'
alias la='ls -a'
alias mkdir='mkdir -p'
alias tree='tree -I node_modules'
alias zmv='noglob zmv -W'

alias -s {html,pug,nunjax,css,scss,js,ts,tsc}='code'

alias gq='cd $(ghq root)/$(ghq list | fzf --preview "bat --color=always --style=header,grid --line-range :80 $(ghq root)/{}/README.*")'
alias hb='hub browse $(ghq list | fzf | cut -d "/" -f 2,3)'

alias g=git
alias gc='g commit'
alias ga='g add'
alias gA='g add -A'
alias gch='g checkout'
alias gf='g fetch'
alias gs='g status'
alias gd='g diff'
alias gdh='g diff HEAD'
alias gdc='g diff --cached'
alias gce='g commit --allow-empty'
alias gca='g commit -a'
alias gl='g log'
alias gso='g show'
alias deco='g log --graph --oneline --decorate=full'
alias fco='g checkout `git branch --all | grep -v HEAD | fzf`'
alias gsw='g switch'
alias gio='g switch --orphan'
alias gr='g restore'
alias grso='g restore --source'
alias grst='g restore --staged'
alias grw='g restore --workspace'
alias gp='g pull'
alias gz='g fuzzy'

alias bri='brew install'

alias ni='npm init'
alias nis='npm install --save'
alias nid='npm install --save-dev'
alias nin='npm install --no-save'
alias nig='npm install -g'
alias nui='npm uninstall --save'
alias nud='npm uninstall --save-dev'
alias nau='npm audit'

alias dc='docker container ls -a --format "{{.Names}}" | fzf'
